version: "3.7"
services:
    # This image is built with slimswitch:
    #   https://github.com/rtckit/eqivo/blob/main/etc/Dockerfile.freeswitch
    freeswitch:
        image: rtckit/eqivo-freeswitch:v1.10.7
        privileged: true
        ports:
            - "5060:5060"
            - "5060:5060/udp"
            - "5066:5066"
            - "8021:8021"
        volumes:
            - ${PWD}/etc/freeswitch.xml:/etc/freeswitch/freeswitch.xml

    eqivo:
        image: rtckit/eqivo
        ports:
            - "8088:8088"
        environment:
            EQIVO_DEFAULT_ANSWER_URL: http://backend/entrypoint
            EQIVO_REST_ALLOWED_IPS: 172.16.0.0/12
            EQIVO_OUTBOUND_ADVERTISED_ADDRESS: inbound_socket_address
            EQIVO_REST_AUTH_ID: dev
            EQIVO_REST_AUTH_TOKEN: ChangeMeAPI
            EQIVO_CORE_0: ChangeMeESL@freeswitch:8021

    frontend:
        image: nginx
        ports:
            - "8081:80"
        volumes:
            - ${PWD}/frontend:/usr/share/nginx/html

    # Built with:
    #
    # docker build --network=host -f ./etc/Dockerfile.backend -t rtckit/eqivo-sandbox-backend ./backend
    backend:
        image: rtckit/eqivo-sandbox-backend
        ports:
            - "8082:80"
        environment:
            EQIVO_BASE_URL: http://eqivo:8088/v0.1/
            EQIVO_REST_AUTH_ID: dev
            EQIVO_REST_AUTH_TOKEN: ChangeMeAPI
        volumes:
            - ${PWD}/backend/src:/opt/backend/src
        working_dir: /opt/backend
        entrypoint: ["./node_modules/nodemon/bin/nodemon.js", "./src/index.js"]
